
GENRE_MAP = {
    "anal": "Anal Play",
    "butt": "Ass Lover",
    "best": "Best / Omnibus",
    "best, omnibus": "Best / Omnibus",
    "omnibus": "Best / Omnibus",
    "breasts": "Beautiful Tits",
    "busty fetish": "Big Tits Lover",
    "electric massager": "Big Vibrator",
    "blow": "Blowjob",
    "restraint": "Bondage",
    "restraints": "Bondage",
    "ropes & ties": "Bondage",
    "bride, young wife": "Bride",
    "young wife": "Bride",
    "cuckold": "Cheating Wife",
    "old playmates": "Childhood Friend",
    "prostitutes": "Club Hostess & Sex Worker",
    "female college student": "College Girl",
    "cosplay costumes": "Cosplay",
    "cosplayers": "Cosplay",
    "cum": "Cum Swallowing",
    "debut production": "Debut",
    "deep throating": "Deep Throat",
    "dirty words": "Dirty Talk",
    "back": "Doggystyle",
    "rolling back eyes / fainting": "Eyes-Roll-Back, Fainting",
    "facials": "Facial",
    "female investigator": "Female Detective",
    "g*******g": "Gang Bang",
    "gangbang": "Gang Bang",
    "fan appreciation": "Fan Appreciation / Home Visit",
    "fan appreciation/ home visit": "Fan Appreciation / Home Visit",
    "home visit": "Fan Appreciation / Home Visit",
    "evil": "Hard Sex",
    "facesitting": "Face Sitting",
    "leg fetish": "Foot Fetish",
    "landlady": "Housewife",
    "big asses": "Huge Butt",
    "huge dick - large dick": "Huge Cock",
    "ultra-huge tits": "Huge Tits",
    "shame": "Humiliation",
    "entertainer": "Idol & Celebrity",
    "image video": "Idol Video",
    "stepfamily": "Incest",
    "kiss kiss": "Kiss",
    "lesbian kiss": "Lesbian",
    "look-alike": "Lookalike",
    "submissive men": "Masochist Man",
    "miniskirt": "Mini Skirt",
    "mother": "MILF",
    "nasty": "Nymphomaniac",
    "nampa": "Picking Up Girls",
    "risky mosaic": "Minimal Mosaic",
    "foreign objects": "Object Insertion",
    "ol": "Office Lady",
    "acme": "Orgasm",
    "acme · orgasm": "Orgasm",
    "outdoor": "Outdoors",
    "4hr+": "Over 4 Hours",
    "mini": "Petite",
    "subjectivity": "POV",
    "impromptu sex ": "Quickie",
    "abuse": "Sadism",
    "sm": "Sadism",
    "sailor suit": "Sailor Uniform",
    "school stuff": "School",
    "schoolgirl": "School Girls",
    "school girl": "School Girls",
    "s********l": "School Girls",
    "academy uniform": "School Uniform",
    "school swimsuit": "School Swimsuits",
    "shaved": "Shaved Pussy",
    "stepmom": "Step-Mother",
    "sweat": "Sweating",
    "3p": "Threesome / Foursome",
    "4p": "Threesome / Foursome",
    "3p, 4p": "Threesome / Foursome",
    "tall": "Tall Girl",
    "body conscious": "Tight Dress",
    "tsundere": "Tsundere",
    "planning": "Variety",
    "cherry boy": "Virgin Man",
    "girl": "Youthful",
}

GENRE_IGNORE_LIST = [
    "sale", "hi-def", "4k", "actress", "avopen", "av open", "fanza", "cinema", "2010s", "other", "quality",
    "daydreamers", "blu-ray", "tv", "jav", "distribution", "sample", "video", "gw great"
]


def get_real_genre(genre):
    result = genre
    for ignore in GENRE_IGNORE_LIST:
        if ignore in genre.lower():
            return None
    if genre.lower() in GENRE_MAP:
        result = GENRE_MAP[genre.lower()]
    result = result.strip()
    return " ".join([w.lower().capitalize() for w in result.split(" ")])
