
GENRE_MAP = {
    "Anal": "Anal Play",
    "Butt": "Ass Lover",
    "Breasts": "Beautiful Tits",
    "Busty Fetish": "Big Tits Lover",
    "Electric Massager": "Big Vibrator",
    "Blow": "Blowjob",
    "Restraint": "Bondage",
    "Restraints": "Bondage",
    "Ropes & Ties": "Bondage",
    "Bride, Young Wife": "Bride",
    "Young Wife": "Bride",
    "BUKKAKE": "Bukkake",
    "Cuckold": "Cheating Wife",
    "Old Playmates": "Childhood Friend",
    "Prostitutes": "Club Hostess & Sex Worker",
    "Female College Student": "College Girl",
    "Cosplay Costumes": "Cosplay",
    "Cosplayers": "Cosplay",
    "Cum": "Cum Swallowing",
    "Debut Production": "Debut",
    "Deep Throating": "Deep Throat",
    "Dirty Words": "Dirty Talk",
    "Back": "Doggystyle",
    "Rolling Back Eyes / Fainting": "Eyes-Roll-Back, Fainting",
    "Female Investigator": "Female Detective",
    "Evil": "Hard Sex",
    "Facesitting": "Face Sitting",
    "Leg Fetish": "Foot Fetish",
    "Landlady": "Housewife",
    "Big Asses": "Huge Butt",
    "Huge Dick - Large Dick": "Huge Cock",
    "Ultra-Huge Tits": "Huge Tits",
    "Shame": "Humiliation",
    "Entertainer": "Idol & Celebrity",
    "Image Video": "Idol Video",
    "Stepfamily": "Incest",
    "KIMONO": "Kimono",
    "Kiss Kiss": "Kiss",
    "Lesbian Kiss": "Lesbian",
    "Look-alike": "Lookalike",
    "Submissive Men": "Masochist Man",
    "Miniskirt": "Mini Skirt",
    "Mother": "MILF",
    "Nasty": "Nymphomaniac",
    "Nampa": "Picking Up Girls",
    "Risky Mosaic": "Minimal Mosaic",
    "Foreign Objects": "Object Insertion",
    "OL": "Office Lady",
    "Acme": "Orgasm",
    "Acme · Orgasm": "Orgasm",
    "Outdoor": "Outdoors",
    "4HR+": "Over 4 Hours",
    "Mini": "Petite",
    "Subjectivity": "POV",
    "Impromptu Sex ": "Quickie",
    "Abuse": "Sadism",
    "SM": "Sadism",
    "Sailor Suit": "Sailor Uniform",
    "School Stuff": "School",
    "S********l": "School Girls",
    "Shaved": "Shaved Pussy",
    "Stepmother": "Stepmom",
    "Sweat": "Sweating",
    "3P" : "Threesome / Foursome",
    "4P" : "Threesome / Foursome",
    "3P, 4P" : "Threesome / Foursome",
    "Tall": "Tall Girl",
    "Body Conscious": "Tight Dress",
    "TSUNDERE": "Tsundere",
    "Planning": "Variety",
    "Cherry Boy": "Virgin Man",
    "Girl": "Youthful",
}

GENRE_IGNORE_LIST = [
    "Sale", "Hi-Def", "4K", "Actress", "AVOPEN", "AV OPEN", "FANZA", "Cinema", "2010s", "Other", "Quality",
    "Daydreamers", "Blu-ray"
]


def get_real_genre(genre):
    for ignore in GENRE_IGNORE_LIST:
        if ignore in genre:
            return None
    if genre in GENRE_MAP:
        return GENRE_MAP[genre]
    return genre
